mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# 分页配置参数
pagehelper:
  page-size-zero: true
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

